<a href="https://colab.research.google.com/github/chinmaya386/Assignmets-python-/blob/main/Pandas_1class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel("/content/Attribute DataSet.xlsx")

In [ ]:
df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
pd.read_excel("/content/Attribute DataSet.xlsx",sheet_name='shan',header=None,names=['a','b','c'])

            a             b          c
0       jnhfk           eww     jcbajb
1  kjvbfbfvkj         dscds   dkawcbab
2  frbfveepoo    dkcdbjkbck   kcbhjbjc
3    nffrnvjn  fhjbhjcvjbwr  4ecndwbkc
4      frbjrb        rfneuv       kbca
5   ecbuferjn      nrejkjer    dwnckje
6   fcbweufbj         rkbev    esnckjn
7     cbewib'         berhj    wefbwkj
8     hrbehjb          fnri       bewk

In [ ]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [ ]:
pd.read_csv('/content/Attribute-DataSet.csv')

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv')

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BCF.csv')

           date  values.I2P  values.P2I  values.JPI
0    1996-04-01   -2.580556   -0.836444        63.3
1    1996-05-01   -2.882258   -1.972581        66.3
2    1996-06-01   -1.742778   -0.478778        59.7
3    1996-07-01   -0.397796   -1.574301        63.3
4    1996-08-01   -0.977151   -1.797312        63.8
..          ...         ...         ...         ...
112  2005-08-01   -2.144935   -1.646989        49.0
113  2005-09-01   -3.543270   -1.769889        49.9
114  2005-10-01   -4.500484   -2.309946        50.6
115  2005-11-01   -4.098556   -1.528611        57.4
116  2005-12-01   -5.797043   -2.872849        52.9

[117 rows x 4 columns]

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/sudh9931/data/main/haberman.csv')

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [ ]:
a= pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [ ]:
type(a)

list

In [ ]:
len(a)

1

In [ ]:
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [ ]:
pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47975,1329257803,PR_kwDOAA0YD848rscP,47975,REF: Move Series logic from Index._get_values_...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Cleaner abstraction.,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47974,1329235469,I_kwDOAA0YD85POoYN,47974,DOC: Signature information for groupby.aggrega...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47973,1329188975,PR_kwDOAA0YD848reOS,47973,TST/CLN: Consolidate creation of groupby metho...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47972,1329187603,PR_kwDOAA0YD848rd7i,47972,BUG: pivot_table raising TypeError with ea dty...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #47477 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47971,1329180699,I_kwDOAA0YD85PObAb,47971,BUG: pivot_table downcasting dtypes even if no...,...,NaT,MEMBER,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47970,1329151254,PR_kwDOAA0YD848rWKR,47970,REF: Use `Styler` implementation for `DataFram...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,"After a year of patching up things in #41649, ...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47964,1328710718,I_kwDOAA0YD85PMoQ-,47964,STYLE check pandas doesn't use external packag...,...,NaT,MEMBER,NaN,NaN,NaN,xref https://github.com/pandas-dev/pandas/pull...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47963,1328495790,I_kwDOAA0YD85PLzyu,47963,BUG: `pd.Grouper` creates empty groups (and in...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47962,1328492289,PR_kwDOAA0YD848pJF5,47962,BUG: read_csv with engine pyarrow doesn't hand...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #47950 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47961,1328449752,I_kwDOAA0YD85PLojY,47961,BUG: read_csv with engine pyarrow doesn't hand...,...,NaT,MEMBER,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47960,1328201471,I_kwDOAA0YD85PKr7_,47960,WEB: Review donation options for pandas,...,NaT,MEMBER,NaN,NaN,NaN,In #47931 @logankilpatrick suggested that we a...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47959,1328191613,I_kwDOAA0YD85PKph9,47959,Specify the behaviour for empty input,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,There isn't an issue for empty inputs. \r\n\r\...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47958,1328169240,PR_kwDOAA0YD848oD6r,47958,ENH: Add `dtype` param for `pandas.Series.str....,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #47872 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47956,1328002838,PR_kwDOAA0YD848ng3Q,47956,Issue46882,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #46882 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47955,1327997065,I_kwDOAA0YD85PJ6CJ,47955,"PERF: .clip with datetime64[ns, UTC] Series re...",...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47953,1327873407,I_kwDOAA0YD85PJb1_,47953,BUG: inconsistent behavior of DateOffset,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47952,1327818649,PR_kwDOAA0YD848m68b,47952,DEBUG: Debug failing macpython wheels,...,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,might be because of a change in hypothesis\r\n,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47950,1327774630,I_kwDOAA0YD85PJDum,47950,BUG: read_csv with engine pyarrow doesn't hand...,...,NaT,MEMBER,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47948,1327654597,PR_kwDOAA0YD848mYuF,47948,DOC: Plotting / Visualization without Jupyter,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Added a note at the top of the page clarifying...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47947,1327607707,PR_kwDOAA0YD848mO3I,47947,BUG: Propagating precision to interval dtype #...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #43913\r\n- [x] [test_frame_equal...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47946,1327602949,PR_kwDOAA0YD848mN6_,47946,Fix bug in pd.merge when joining two Series,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47944,1327408033,I_kwDOAA0YD85PHqOh,47944,BUG: Ordering of `columns` is not preserved in...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47942,1327099266,I_kwDOAA0YD85PGe2C,47942,BUG: Resampler.quantile produce inconsistent r...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47941,1326954849,I_kwDOAA0YD85PF7lh,47941,BUG: union of lists of DatetimeIndex generates...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47937,1326736134,PR_kwDOAA0YD848jTMa,47937,WARN : extended stack level check to include a...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #47919 \r\n- [ ] All [code checks...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47936,1326723599,PR_kwDOAA0YD848jQhX,47936,CLN: remove deprecated DEF,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,xref https://github.com/cython/cython/issues/4...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47935,1326553093,PR_kwDOAA0YD848itEe,47935,Fix out-of-bounds heap access in internals.pyx.,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,"If blknos is empty, we unconditionally access ...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47934,1326492015,PR_kwDOAA0YD848ig4l,47934,ENH: copy kwd for add_suffix/add_prefix,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47933,1326333380,I_kwDOAA0YD85PDj3E,47933,nightly builds failing since 19 July on MacPyt...,...,NaT,MEMBER,NaN,NaN,NaN,https://dev.azure.com/pandas-dev/pandas-wheels...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47932,1326170455,PR_kwDOAA0YD848hand,47932,ENH: copy keyword to set_axis,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,This also opens the option of deprecating `inp...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [ ]:
js=pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')

In [ ]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app', 'state_reason'],
      dtype='object')

In [ ]:
js['user']

0     {'login': 'jbrockmendel', 'id': 8078968, 'node...
1     {'login': 'DRudel', 'id': 5006589, 'node_id': ...
2     {'login': 'rhshadrach', 'id': 45562402, 'node_...
3     {'login': 'phofl', 'id': 61934744, 'node_id': ...
4     {'login': 'phofl', 'id': 61934744, 'node_id': ...
5     {'login': 'attack68', 'id': 24256554, 'node_id...
6     {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
7     {'login': 'bollard', 'id': 358225, 'node_id': ...
8     {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
9     {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
10    {'login': 'datapythonista', 'id': 10058240, 'n...
11    {'login': 'Th3nn3ss', 'id': 25160953, 'node_id...
12    {'login': 'JeffersonQin', 'id': 30655701, 'nod...
13    {'login': 'Mehgarg', 'id': 65103188, 'node_id'...
14    {'login': 'jreback', 'id': 953992, 'node_id': ...
15    {'login': 'colomb8', 'id': 71855882, 'node_id'...
16    {'login': 'phofl', 'id': 61934744, 'node_id': ...
17    {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
18    {'login': 'tpackard1', 'id': 46908522, 'node_i...
19    {'login': 'SomtochiUmeh', 'id': 74836691, 'nod...
20    {'login': 'nsarang', 'id': 25885841, 'node_id'...
21    {'login': 'galipremsagar', 'id': 11664259, 'no...
22    {'login': 'henrykwong', 'id': 20166805, 'node_...
23    {'login': 'btodac', 'id': 45459748, 'node_id':...
24    {'login': 'shourya5', 'id': 73142986, 'node_id...
25    {'login': 'fangchenli', 'id': 7614606, 'node_i...
26    {'login': 'hawkinsp', 'id': 348932, 'node_id':...
27    {'login': 'jbrockmendel', 'id': 8078968, 'node...
28    {'login': 'simonjayhawkins', 'id': 13159005, '...
29    {'login': 'jbrockmendel', 'id': 8078968, 'node...
Name: user, dtype: object